version: "2"
services:
  django:
    container_name: django_server_cryptech
    build:
      context: .
      dockerfile: Dockerfile
    image: docker_tutorial_django
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/cryptech
    ports:
      - "8000:8000"